### GET ALL CATALOG ITEMS FOR PAGE 0
GET http://localhost:8085/api/v1/catalog/items HTTP/1.1

### GET 3 CATALOG ITEMS FOR PAGE 1
GET http://localhost:8085/api/v1/catalog/items?pageIndex=1&pageSize=3 HTTP/1.1

### GET ITEMS FOR IDS 4,5,6
GET http://localhost:8085/api/v1/catalog/items?ids=4,5,6 HTTP/1.1

### GET ITEM WITH ID 5
GET http://localhost:8085/api/v1/catalog/items/5 HTTP/1.1

### GET NON EXISTING ITEM
GET http://localhost:8085/api/v1/catalog/items/26 HTTP/1.1

### GET ITEM WITH NAME LIKE
GET http://localhost:8085/api/v1/catalog/items/withname/.net HTTP/1.1

### GET ITEMS WITH TYPE 1 AND BRAND 1
GET http://localhost:8085/api/v1/catalog/items/type/1/brand/2 HTTP/1.1

### GET ITEMS WITH TYPE 1
GET http://localhost:8085/api/v1/catalog/items/type/1 HTTP/1.1

### GET ITEMS WITH BRAND 2
GET http://localhost:8085/api/v1/catalog/items/type/all/brand/2 HTTP/1.1

### GET ITEMS WITH BRAND 2
GET http://localhost:8085/api/v1/catalog/items/type/all/brand/2 HTTP/1.1

### GET ITEMS FOR IDS 4,5,6
GET http://localhost:8085/api/v1/catalog/items?ids=4,5,6 HTTP/1.1

### GET CATALOG TYPES
GET http://localhost:8085/api/v1/catalog/catalogTypes HTTP/1.1

### GET CATALOG BRANDS
GET http://localhost:8085/api/v1/catalog/catalogBrands HTTP/1.1

### CREATE A TEST PRODUCT
POST http://localhost:8085/api/v1/catalog/items HTTP/1.1
Content-Type: application/json

{   
      "name": "Test Product",
      "description": "Test Product description",
      "price":75.5,
      "pictureFileName": "testproduct.png",
      "availableStock": 29,
      "restockThreshold": 31,
      "maxStockThreshold": 33,
      "onReorder": false,
      "catalogBrandId": 2,
      "catalogTypeId": 2
}

### UPDATE PRODUCT ATTRIBUTES EXCLUDING PRICE
PUT  http://localhost:8085/api/v1/catalog/items HTTP/1.1
Content-Type: application/json

{   
      "id" : 15,
      "name": "TEST PRODUCT",
      "description": "TEST PRODUCT DESCRIPTION",
      "price": 75.5,
      "pictureFileName": "testproduct.png",
      "availableStock": 11,
      "restockThreshold": 22,
      "maxStockThreshold": 44,
      "onReorder": false,
      "catalogBrandId": 1,
      "catalogTypeId": 1
}

### UPDATE PRODUCT PRICE FOR EXISTING ITEM
PUT  http://localhost:8085/api/v1/catalog/items HTTP/1.1
Content-Type: application/json

{   
      "id" : 15,
      "name": "TEST PRODUCT",
      "description": "TEST PRODUCT DESCRIPTION",
      "price": 23.5,
      "pictureFileName": "testproduct.png",
      "availableStock": 11,
      "restockThreshold": 22,
      "maxStockThreshold": 44,
      "onReorder": false,
      "catalogBrandId": 1,
      "catalogTypeId": 1
}

### UPDATE PRODUCT PRICE FOR NON EXISTING ITEM
PUT  http://localhost:8085/api/v1/catalog/items HTTP/1.1
Content-Type: application/json

{   
      "id" : 95,
      "name": "TEST PRODUCT",
      "description": "TEST PRODUCT DESCRIPTION",
      "price": 23.5,
      "pictureFileName": "testproduct.png",
      "availableStock": 11,
      "restockThreshold": 22,
      "maxStockThreshold": 44,
      "onReorder": false,
      "catalogBrandId": 1,
      "catalogTypeId": 1
}

### DELETE PRODUCT WITH ID 
DELETE http://localhost:8085/api/v1/catalog/items/15 HTTP/1.1


